### ISSUE TITLE
multiple calendars broadcasting overlay each other

### ISSUE THREAD

**Issue by sdetweil** [MMRIZE/MMM-CalendarExt3Agenda#13]
EXT3 makes a pool of the entries
Agenda does not 

we tried with two calendar module instances , one url each
or 1 calendar modules instance with 2 urls.. 

the default cal module broadcasts for each URL regardless of instance

**Comment by eouia** [comment]
More details I need. Show me the config and ical urls

**Comment by eouia** [comment]
Ah you’re right. It would be fixed on next update soon

**Comment by sdetweil** [comment]
also, haven't found cause, but two calls

name:"Fred" and name:"Sue"

calendarSet:["Sue"]

agenda for Sue appears

Fred calendar broadcasts, suddenly Feed agenda appears.

so in overlaying data  the calendarSet  filter is lost. it should have gone to no display if only Fred cal data

**Comment by sdetweil** [comment]
is

**Comment by eouia** [comment]
I'll check. I'm on the business trip now so next update will be done 2 weeks later.

**Comment by sdetweil** [comment]
no problem, no hurry, safe travels

**Comment by eouia** [comment]
Fixed. #12(#19)
