### ISSUE TITLE
eventFilter/eventTransformer not working

### ISSUE THREAD

**Issue by zanix** [MMRIZE/MMM-CalendarExt3Agenda#20]
Both `eventFilter` and `eventTransformer` stopped working in version 1.2.
It seems like Agenda never calls these functions. If I revert to v1.1.5 these callbacks work again.

Version 1.1.3 of CalendarExt3 seems to work though

**Comment by eouia** [comment]
You are right. I'll fix it.

**Comment by zanix** [comment]
Update works, thanks!
