### ISSUE TITLE
Request of table like in MMM-CalendarExtPlan

### ISSUE THREAD

**Issue by JoChenSchae** [MMRIZE/MMM-CalendarExt3Agenda#28]
Hi.
Is it possible to change the Agenda to a table view like in MMM-CalendarExtPlan?
Defining three or more diffent calendarSet (former: criteria), which will work as columns in a table.

At the moment I use 3 instance of the module, but the cell height differs for each calendar.
Also the date is written 3 times, which is not needed.

I tried to solve this issue with the custom.css, but this doesnt workout, because I can't split the events in the cellBody.
Many thanks in advance.

**Comment by eouia** [comment]
Unfortunately not yet. I have a plan to implement that feature, but not soon.

**Comment by eouia** [comment]
Try [MMM-CalendarExt3Journal](https://github.com/MMRIZE/MMM-CalendarExt3Journal)
