### ISSUE TITLE
Duplicate Events

### ISSUE THREAD

**Issue by xeryax** [MMRIZE/MMM-CalendarExt3Agenda#41]
Heyo-
Sorry if this is a newb question/non-issue... Im new to MagicMirror, i am using MMM-GoogleCalendar to pull in my wifes and my calendars, naturally we have some things that are on both of our calendars, and unfortunately, these events are duplicated on each day of the agenda.
I've got my GoogleCalendar on the page as well as the agenda just so you can see that hideduplicates is working in my MMM-GoogleCalendar module, but not working in this module.

Could you help me figure out how to make this work, or let me know if this is just an unimplemented feature?  Thank you!
![image](https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/26824412/99dc3e63-d63d-4986-a0cc-441127b7105e)

**Comment by eouia** [comment]
This module doesn’t consider duplicated events because parsing itself is delegated to other module. So the event provider module should do that kind of processing before delivery of events.
Anyway, I think I can make an update or hack for it, but recently I’m somehow busy for my job. Plz wait a while.

**Comment by xeryax** [comment]
Thanks for considering working up a hack! I appreciate that- take your time, ive got Dakboard for another few months, so im in no hurry.
I appreciate the response!

**Comment by eouia** [comment]
Updated. (#42)

- `skipDuplicated: false,`
<img width="293" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1720610/4c6248ea-8fcb-4e5f-9e9a-e05a99a71db4">

- `skipDuplicated: true,` (default)
<img width="293" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1720610/22741415-c926-4019-8442-67fa551f52d2">
