### ISSUE TITLE
Google family Calendar events are not shown

### ISSUE THREAD

**Issue by Thommes85** [MMRIZE/MMM-CalendarExt3Agenda#49]
I'm currently using 3 Google Calendars with the module.
1 containing the local holidays
1 that is maintained by someone else
1 family calendar, that is shared with the family members
The first two work like a charm.
The events from my Google family calendar, however, are not shown in the module.
I've tried the public .ics Link and also the private .ics Link.
When I start up MagicMirror, the Calendar-Fetcher gets the events from the all calendars is working fine. However, the events of my family calendar are not shown in the module.
Also I noticed, that the Calendar-Fetcher always fetches n+1 events. If my calendar has 4 events, the Calendar-Fetcher fetches 5 events, is that intentional?

**Comment by eouia** [comment]
`Calendar-Fetching` is not CX*'s job. It is done by `default calendar` module.
Anyway, about Google `Family` calendar, it doesn't provide any public/private ics URL. You may confuse some terms, `Public URL to this calendar`, It is not `ics`, it is just a link of Google Calendar page.
 
 To check your calendar or event is retrieving properly, See the default calendar's view. Once it shown there, it will be shown in CX* module also.
 
 To use Google `Family` calendar, I recommend to get a help of `MMM-CalDAV`. It will make a private ics URL from Google Calendar CalDAV server.
