### ISSUE TITLE
Title doesn't show up

### ISSUE THREAD

**Issue by Dennis-Rosenbaum** [MMRIZE/MMM-CalendarExt3Agenda#60]
Hey there, love your work here.

Small issue, the title of the module doesn't show up.

This is my config
![image](https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1788426/620ddde2-b6fb-4e34-983f-d3a55d5d77d3)

This is the result
<img width="331" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1788426/20a50ca0-54ff-4101-b60a-14d28f990cac">

**Comment by Dennis-Rosenbaum** [comment]
Header property does work though. In that case only readme must be changed.

![image](https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1788426/0ad4845c-d425-49da-aab3-1754fe66737c)

**Comment by eouia** [comment]
Thanks. It was my fault. I'll keep in mind and fix it on next update.
