### ISSUE TITLE
Today's Events not showing on Agenda

### ISSUE THREAD

**Issue by xeryax** [MMRIZE/MMM-CalendarExt3Agenda#62]
I have 3 events left on the calendar today, the GoogleCalendar module is showing these items, but this module is not:

Other weird, and maybe relevant item... having a startDayIndex of -1 or 0 makes the module not show at all, I used to have the value set to zero and things worked, but recently (last 2 days) it stopped working.

**Comment by eouia** [comment]
Could you share me your config and ics url/file. And where you live(time zone).
send me eouia0819@gmail.com

**Comment by xeryax** [comment]
Thanks, emailed.

**Comment by gddhub** [comment]
I have events on almost every day across three different calendars. The events load just fine in MMM-CalendarExt3 but only one event from yesterday on one calendar loads in MMM-CalendarExt3Agenda. My entry in config is:

		{
			module: "MMM-CalendarExt3Agenda",
			header: "Agenda",
			position: "top_left",
			config: {
				showMiniMonthCalendar: false,
				locale: "en-US",
				startDayIndex: -1,
				endDayIndex: 3,
				useIconify: false,
				calendarSet:[]
			}
		},

**Comment by xeryax** [comment]
Looks good, though it seems like we will have to wait until the end of the month to know for sure ;)

Thanks for the update!

**Comment by eouia** [comment]
@xeryax Maybe you can test it with `startDayIndex: 25`, `endDayIndex: 35`.
